<?php

namespace Database\Seeders;

use App\Models\Medication;
use Illuminate\Database\Seeder;

class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $medications = [
            ['name' => 'Paracetamol 500mg', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Panadol', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Panadol Hijau', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Panadol Biru', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Sanmol', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Tempra', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Pamol', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Ibuprofen', 'category' => 'NSAID'],
            ['name' => 'Proris', 'category' => 'NSAID'],
            ['name' => 'Brufen', 'category' => 'NSAID'],
            ['name' => 'Methylprednisolone 4mg', 'category' => 'Kortikosteroid'],
            ['name' => 'Cetirizine', 'category' => 'Antihistamin'],
            ['name' => 'Incidal', 'category' => 'Antihistamin'],
            ['name' => 'Alleron', 'category' => 'Antihistamin'],
            ['name' => 'Demacolin', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Mixagrip', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Decolgen', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Mylanta', 'category' => 'Antasida/Gastro'],
            ['name' => 'Promag', 'category' => 'Antasida/Gastro'],
            ['name' => 'Promagh Cair', 'category' => 'Antasida/Gastro'],
            ['name' => 'Polysilane', 'category' => 'Antasida/Gastro'],
            ['name' => 'Betadine', 'category' => 'Antiseptik'],
            ['name' => 'Betadine Gargle', 'category' => 'Antiseptik'],
            ['name' => 'Betadine Solution', 'category' => 'Antiseptik'],
            ['name' => 'Caladine Cair', 'category' => 'Topikal/Kulit'],
            ['name' => 'Caladine Lotion', 'category' => 'Topikal/Kulit'],
            ['name' => 'Cenfresh Mini Dose', 'category' => 'Tetes Mata'],
            ['name' => 'Cendo Fresh', 'category' => 'Tetes Mata'],
            ['name' => 'Cendo Lyteers', 'category' => 'Tetes Mata'],
            ['name' => 'Counterpain', 'category' => 'Topikal/Nyeri Otot'],
            ['name' => 'Hotin Cream', 'category' => 'Topikal/Nyeri Otot'],
            ['name' => 'Hansaplast', 'category' => 'Alat/Perban'],
            ['name' => 'Sangobion', 'category' => 'Suplemen'],
            ['name' => 'Hemobion', 'category' => 'Suplemen'],
            ['name' => 'Enervon C', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Enervon Active', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Oxycan', 'category' => 'Respirasi'],
            ['name' => 'Amoxicillin 500mg', 'category' => 'Antibiotik'],
            ['name' => 'Amoxicillin Syrup', 'category' => 'Antibiotik'],
            ['name' => 'Cotrimoxazole', 'category' => 'Antibiotik'],
            ['name' => 'Cefadroxil', 'category' => 'Antibiotik'],
            ['name' => 'Ciprofloxacin', 'category' => 'Antibiotik'],
            ['name' => 'Antasida DOEN', 'category' => 'Antasida/Gastro'],
            ['name' => 'OBH Combi', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Vicks Formula 44', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Loratadine', 'category' => 'Antihistamin'],
            ['name' => 'Chlorpheniramine Maleate (CTM)', 'category' => 'Antihistamin'],
            ['name' => 'Salbutamol', 'category' => 'Respirasi'],
            ['name' => 'Dexamethasone', 'category' => 'Kortikosteroid'],
            ['name' => 'Oralit', 'category' => 'Rehidrasi'],
            ['name' => 'Vitamin B Complex', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Vitamin C 500mg', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Vitamin D3', 'category' => 'Vitamin/Suplemen'],

            ['name' => 'Paracetamol Syrup', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Paracetamol Drop', 'category' => 'Analgesik/Antipiretik'],
            ['name' => 'Asam Mefenamat 500mg', 'category' => 'NSAID'],
            ['name' => 'Asam Mefenamat 250mg', 'category' => 'NSAID'],
            ['name' => 'Natrium Diklofenak 50mg', 'category' => 'NSAID'],
            ['name' => 'Ketoprofen Gel', 'category' => 'Topikal/Nyeri Otot'],
            ['name' => 'Omeprazole 20mg', 'category' => 'Gastro/Asam Lambung'],
            ['name' => 'Lansoprazole 30mg', 'category' => 'Gastro/Asam Lambung'],
            ['name' => 'Ranitidine', 'category' => 'Gastro/Asam Lambung'],
            ['name' => 'Domperidone 10mg', 'category' => 'Anti Mual'],
            ['name' => 'Metoclopramide', 'category' => 'Anti Mual'],
            ['name' => 'Dimenhydrinate', 'category' => 'Anti Mual'],
            ['name' => 'Attapulgite', 'category' => 'Antidiare'],
            ['name' => 'Loperamide', 'category' => 'Antidiare'],
            ['name' => 'Zinc Sulfate', 'category' => 'Suplemen'],
            ['name' => 'ORS 200ml', 'category' => 'Rehidrasi'],
            ['name' => 'Procold', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Neozep', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Bodrex Flu & Batuk', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Bodrexin', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Komix', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Siladex', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Woods', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Ambroxol', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Guaifenesin', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Dextromethorphan', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Pseudoephedrine', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Phenylpropanolamine', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Bromhexine', 'category' => 'Flu/Batuk/Pilek'],
            ['name' => 'Acyclovir Cream', 'category' => 'Antivirus/Topikal'],
            ['name' => 'Clotrimazole Cream', 'category' => 'Antijamur/Topikal'],
            ['name' => 'Ketoconazole Cream', 'category' => 'Antijamur/Topikal'],
            ['name' => 'Miconazole Cream', 'category' => 'Antijamur/Topikal'],
            ['name' => 'Hydrocortisone Cream', 'category' => 'Topikal/Kulit'],
            ['name' => 'Gentamicin Ointment', 'category' => 'Antibiotik/Topikal'],
            ['name' => 'Bioplacenton', 'category' => 'Antibiotik/Topikal'],
            ['name' => 'Nebacetin Ointment', 'category' => 'Antibiotik/Topikal'],
            ['name' => 'Rivanol', 'category' => 'Antiseptik'],
            ['name' => 'Povidone Iodine', 'category' => 'Antiseptik'],
            ['name' => 'Alkohol 70%', 'category' => 'Antiseptik'],
            ['name' => 'Kasa Steril', 'category' => 'Alat/Perban'],
            ['name' => 'Plester Roll', 'category' => 'Alat/Perban'],
            ['name' => 'Plester Kain', 'category' => 'Alat/Perban'],
            ['name' => 'Perban Elastis', 'category' => 'Alat/Perban'],
            ['name' => 'Kapas Medis', 'category' => 'Alat/Perban'],
            ['name' => 'Masker Medis', 'category' => 'Alat/Perban'],
            ['name' => 'Sarung Tangan Medis', 'category' => 'Alat/Perban'],
            ['name' => 'Cavicur', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Redoxon', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Imboost', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Curcuma Plus', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Becom-Zet', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Vitacimin', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Vitamin E', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Calcium Lactate', 'category' => 'Vitamin/Suplemen'],
            ['name' => 'Ferrous Sulfate', 'category' => 'Suplemen'],
            ['name' => 'Asam Folat', 'category' => 'Suplemen'],
            ['name' => 'Albendazole', 'category' => 'Antiparasit'],
            ['name' => 'Pirantel Pamoat', 'category' => 'Antiparasit'],
            ['name' => 'Metronidazole', 'category' => 'Antibiotik/Antiprotozoa'],
            ['name' => 'Azithromycin 500mg', 'category' => 'Antibiotik'],
            ['name' => 'Erythromycin', 'category' => 'Antibiotik'],
            ['name' => 'Levofloxacin', 'category' => 'Antibiotik'],
            ['name' => 'Doxycycline', 'category' => 'Antibiotik'],
            ['name' => 'Cefixime', 'category' => 'Antibiotik'],
            ['name' => 'Ceftriaxone', 'category' => 'Antibiotik'],
            ['name' => 'Mupirocin Ointment', 'category' => 'Antibiotik/Topikal'],
            ['name' => 'Asiklovir Tablet', 'category' => 'Antivirus'],
            ['name' => 'Nasal Saline Spray', 'category' => 'Respirasi'],
            ['name' => 'Ventolin Inhaler', 'category' => 'Respirasi'],
            ['name' => 'Budesonide Nebule', 'category' => 'Respirasi'],
            ['name' => 'Prednisone', 'category' => 'Kortikosteroid'],
            ['name' => 'Loperamide Syrup', 'category' => 'Antidiare'],
            ['name' => 'Simethicone', 'category' => 'Antasida/Gastro'],
            ['name' => 'Hyoscine Butylbromide', 'category' => 'Antispasmodik'],
        ];

        $payload = collect($medications)
            ->map(function (array $item) use ($now) {
                return [
                    'name' => trim($item['name']),
                    'category' => $item['category'],
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            })
            ->unique('name')
            ->values()
            ->all();

        Medication::upsert($payload, ['name'], ['category', 'updated_at']);
    }
}

